#!/bin/bash

# get system time
min=$(date +%M) #[0, 59]
hour=$(date +%l) #[1, 12]

fuz_bucket=$(((min+2)/5))

# increment hour for next hour
if (( fuz_bucket > 6 )); then
    hour=$((hour+1))
    if (( hour == 13 )); then
        hour=1
    fi
fi

case $fuz_bucket in
    0)
        fuz_str='o'\''clock'
        ;;
    1)
        fuz_str='five'
        ;;
    2)
        fuz_str='ten'
        ;;
    3)
        fuz_str='quarter'
        ;;
    4)
        fuz_str='twenty'
        ;;
    5)
        fuz_str='twenty five'
        ;;
    6)
        fuz_str='half'
        ;;
    7)
        fuz_str='twenty five'
        ;;
    8)
        fuz_str='twenty'
        ;;
    9)
        fuz_str='quarter'
        ;;
    10)
        fuz_str='ten'
        ;;
    11)
        fuz_str='five'
        ;;
    12)
        fuz_str='o'\''clock'
        ;;
esac

case $hour in
    1)
        hour_str='one'
        ;;
    2)
        hour_str='two'
        ;;
    3)
        hour_str='three'
        ;;
    4)
        hour_str='four'
        ;;
    5)
        hour_str='five'
        ;;
    6)
        hour_str='six'
        ;;
    7)
        hour_str='seven'
        ;;
    8)
        hour_str='eight'
        ;;
    9)
        hour_str='nine'
        ;;
    10)
        hour_str='ten'
        ;;
    11)
        hour_str='eleven'
        ;;
    12)
        hour_str='twelve'
        ;;
esac

case $fuz_bucket in
    0|12)
        echo "$hour_str $fuz_str"
        ;;
    1|2|3|4|5|6)
        echo "$fuz_str past $hour_str"
        ;;
    7|8|9|10|11)
        echo "$fuz_str to $hour_str"
        ;;
esac
